export const faqContent = {
  en: {
    title: 'Frequently Asked Questions',
    items: [
      { q: 'What does Buried Games Studio specialize in?', a: 'Buried Games Studio specializes in indie game development — multiplayer games, trivia apps, social deduction games, and interactive digital experiences, built with Unity, Unreal Engine, and modern web technologies like Next.js.' },
      { q: 'What games has Buried Games Studio developed?', a: 'Our portfolio includes Nabsh (an online trivia game), KoutQ8 (a digital version of the traditional Kuwaiti card game Kout), Power of Bombs (a multiplayer arcade game), Arrab (a real-time social deduction Mafia game), Luna Fantasy (a web RPG), and Gathered by the Light (a pixel-art adventure).' },
      { q: 'What game engines do you use?', a: 'We build with Unity, Unreal Engine, and modern web technologies like Next.js and NestJS, depending on the project\'s scope, genre, and target platform.' },
      { q: 'What platforms are your games available on?', a: 'Our games span web browsers, mobile (iOS & Android), and PC. Web titles play right in the browser, while PC releases go out through platforms like Steam and itch.io as well as direct download from our website.' },
      { q: 'Where is Buried Games Studio located?', a: 'Buried Games Studio is a remote-first studio rooted in the Gulf, working with clients across Kuwait, Saudi Arabia, the UAE, Qatar, Bahrain, and Oman. We collaborate remotely so distance is never a barrier to building a great game together.' },
      { q: 'How much does game development cost?', a: 'There is no single price tag — cost depends on scope, platform, art style, and whether you need multiplayer or live operations. A small mobile prototype and a full cross-platform title sit at very different budgets. Tell us what you have in mind through our contact form and we will scope it honestly and give you a realistic estimate.' },
      { q: 'Do you build games for clients in Saudi Arabia and the UAE?', a: 'Yes. We are a game development studio serving clients across the GCC, including Kuwait, Saudi Arabia, the UAE, Qatar, Bahrain, and Oman. We work remotely with studios, brands, and entrepreneurs throughout the region from concept to launch.' },
      { q: 'Do you develop games in Arabic?', a: 'Yes. We design and build games with full Arabic language support and right-to-left interfaces, and we understand the GCC market and its players first-hand — KoutQ8, our digital take on the traditional Kuwaiti card game, is one example of culturally rooted work.' },
      { q: 'Do you teach game development?', a: 'Yes, we publish game development tutorials, devlogs, and tips on our official YouTube channel, covering Unity, Unreal Engine, and indie game production.' },
      { q: 'How can I collaborate with Buried Games Studio?', a: 'We\'re open to partnerships, publishing, and creative collaborations. Please use the contact form or reach out via WhatsApp/email to connect with our team.' },
      { q: 'Can I submit a game idea to you?', a: 'We appreciate the enthusiasm! However, for legal reasons, we cannot accept unsolicited game ideas or submissions. We focus on developing our original in-house projects.' },
      { q: 'How can I stay updated on new games and announcements?', a: 'The best way to stay in the loop is by following us on our social media channels like YouTube, Twitter, and Instagram! You can find all the links in our website footer.' },
      { q: 'Do you offer internships or job opportunities?', a: 'We post any available job or internship openings on our LinkedIn page. We recommend following us there for the latest career opportunities at Buried Games Studio.' },
    ],
  },
  ar: {
    title: 'الأسئلة الشائعة',
    items: [
      { q: 'ما هو تخصص استوديو بريد جيمز؟', a: 'يختص استوديو بريد جيمز في تطوير الألعاب المستقلة — ألعاب جماعية، وتطبيقات تريفيا، وألعاب خداع اجتماعي، وتجارب رقمية تفاعلية، باستخدام Unity وUnreal Engine وتقنيات الويب الحديثة مثل Next.js.' },
      { q: 'ما هي الألعاب التي طورها استوديو بريد جيمز؟', a: 'تضم مجموعتنا لعبة نبش (لعبة تريفيا جماعية أونلاين)، وكوت (نسخة رقمية من لعبة الكوت الكويتية التقليدية)، وباور أوف بومبز (لعبة أكشن جماعية)، والعرّاب (لعبة مافيا وخداع اجتماعي في الوقت الفعلي)، ولونا فانتازيا (لعبة آر بي جي على الويب)، ومجتمعون بالنور (لعبة مغامرات بأسلوب البكسل آرت).' },
      { q: 'ما هي محركات الألعاب التي تستخدمونها؟', a: 'نبني ألعابنا باستخدام Unity وUnreal Engine وتقنيات الويب الحديثة مثل Next.js وNestJS، اعتمادًا على نطاق المشروع ونوعه والمنصة المستهدفة.' },
      { q: 'على أي منصات تتوفر ألعابكم؟', a: 'تتوفر ألعابنا على متصفحات الويب، والجوال (iOS و Android)، والحاسوب. ألعاب الويب تعمل مباشرة في المتصفح، بينما تُطلق إصدارات الحاسوب عبر منصات مثل Steam وitch.io إضافة إلى التحميل المباشر من موقعنا.' },
      { q: 'أين يقع مقر استوديو بريد جيمز؟', a: 'استوديو بريد جيمز استوديو يعمل عن بُعد ومتجذر في الخليج، نخدم العملاء في الكويت والسعودية والإمارات وقطر والبحرين وعُمان. نتعاون عن بُعد، فالمسافة لا تقف يومًا عائقًا أمام بناء لعبة رائعة معًا.' },
      { q: 'كم تكلفة تطوير لعبة؟', a: 'لا يوجد سعر ثابت واحد — تعتمد التكلفة على نطاق المشروع والمنصة وأسلوب الفن وما إذا كنت بحاجة إلى تجربة جماعية أو عمليات حية. النموذج الأولي البسيط للجوال واللعبة الكاملة متعددة المنصات يقعان عند ميزانيتين مختلفتين تمامًا. أخبرنا بفكرتك عبر نموذج الاتصال وسنحدد نطاقها بصدق ونمنحك تقديرًا واقعيًا.' },
      { q: 'هل تطورون ألعابًا لعملاء في السعودية والإمارات؟', a: 'نعم. نحن استوديو تطوير ألعاب نخدم العملاء في مختلف دول الخليج، بما في ذلك الكويت والسعودية والإمارات وقطر والبحرين وعُمان. نعمل عن بُعد مع الاستوديوهات والعلامات التجارية ورواد الأعمال في المنطقة من الفكرة إلى الإطلاق.' },
      { q: 'هل تطورون ألعابًا باللغة العربية؟', a: 'نعم. نصمم ونبني ألعابًا بدعم كامل للغة العربية وواجهات من اليمين إلى اليسار، ونفهم سوق الخليج ولاعبيه عن قرب — ولعبة كوت، نسختنا الرقمية من لعبة الكوت الكويتية التقليدية، خير مثال على العمل المتجذر ثقافيًا.' },
      { q: 'هل تقدمون دروسًا في تطوير الألعاب؟', a: 'نعم، ننشر دروسًا تعليمية وسجلات تطوير ونصائح على قناتنا الرسمية في يوتيوب، تغطي Unity وUnreal Engine وإنتاج الألعاب المستقلة.' },
      { q: 'كيف يمكنني التعاون مع استوديو بريد جيمز؟', a: 'نحن منفتحون على الشراكات وفرص النشر والتعاونات الإبداعية. يرجى استخدام نموذج الاتصال أو التواصل عبر واتساب/البريد الإلكتروني للتواصل مع فريقنا.' },
      { q: 'هل يمكنني تقديم فكرة لعبة لكم؟', a: 'نحن نقدر حماسكم! ومع ذلك، لأسباب قانونية، لا يمكننا قبول أفكار أو تقديمات ألعاب غير مرغوب فيها. نحن نركز على تطوير مشاريعنا الداخلية الأصلية.' },
      { q: 'كيف يمكنني البقاء على اطلاع بألعابكم وإعلاناتكم الجديدة؟', a: 'أفضل طريقة للبقاء على اطلاع هي متابعتنا على قنوات التواصل الاجتماعي الخاصة بنا مثل يوتيوب وتويتر وإنستغرام! يمكنك العثور على جميع الروابط في تذييل موقعنا.' },
      { q: 'هل تقدمون فرص تدريب أو وظائف؟', a: 'نقوم بنشر أي فرص عمل أو تدريب متاحة على صفحتنا في LinkedIn. نوصي بمتابعتنا هناك للحصول على أحدث الفرص الوظيفية في استوديو بريد جيمز.' },
    ],
  },
};
