
export const gamesContent = [
  {
    id: 'arrab',
    slug: 'arrab',
    title: 'Arrab',
    status: 'development',
    engine: 'Next.js / NestJS',
    logoUrl: 'https://assets.buriedgames.com/images/games/arrab/logo.png',
    description: {
      en: 'The ultimate social deduction experience — a premium multiplayer Mafia game with real-time gameplay, 11 unique roles, and a cinematic noir atmosphere.',
      ar: 'تجربة الخداع الاجتماعي المطلقة — لعبة مافيا متعددة اللاعبين بأجواء سينمائية، 11 دورًا فريدًا، ولعب جماعي في الوقت الفعلي.',
    },
    longDescription: {
      en: 'Arrab (العراب) is a premium web-based Mafia/Werewolf game designed as the definitive social deduction experience for the Arab world. Featuring 11 unique roles across three teams — Mafia, Town, and Neutral — players engage in strategic deception through day discussions, nighttime actions, and dramatic voting eliminations. With a cinematic "Midnight Lounge" aesthetic, real-time multiplayer via Socket.IO, and full Arabic/English bilingual support, Arrab transforms classic party gameplay into a polished digital experience.',
      ar: 'العرّاب هي لعبة مافيا/ذئب متعددة اللاعبين مصممة كتجربة خداع اجتماعي نهائية للعالم العربي. تضم 11 دورًا فريدًا عبر ثلاث فرق — المافيا والمدينة والمحايد — يشارك اللاعبون في خداع استراتيجي عبر مناقشات نهارية وأفعال ليلية وتصويت درامي. بجماليات "الصالة الليلية" السينمائية واللعب الجماعي في الوقت الفعلي ودعم ثنائي اللغة، يحوّل العرّاب لعب الحفلات الكلاسيكي إلى تجربة رقمية مصقولة.',
    },
    features: [
      { icon: 'Users', title: { en: 'Real-Time Multiplayer', ar: 'لعب جماعي مباشر' }, description: { en: 'Play with friends in real-time via Socket.IO — designed for in-person game nights with digital moderation.', ar: 'العب مع الأصدقاء في الوقت الفعلي — مصمم لليالي اللعب الجماعي مع إدارة رقمية.' } },
      { icon: 'ShieldCheck', title: { en: '11 Unique Roles', ar: '11 دورًا فريدًا' }, description: { en: 'From the Godfather to the Jester — each role has unique night actions and win conditions across three teams.', ar: 'من العرّاب إلى المهرج — لكل دور أفعال ليلية فريدة وشروط فوز عبر ثلاث فرق.' } },
      { icon: 'Bolt', title: { en: 'Cinematic Design', ar: 'تصميم سينمائي' }, description: { en: 'A premium "Midnight Lounge" aesthetic with ornate role icons, ambient soundscapes, and immersive animations.', ar: 'جماليات "الصالة الليلية" الفاخرة مع أيقونات أدوار مزخرفة وأصوات محيطة ورسوم متحركة غامرة.' } },
      { icon: 'Globe', title: { en: 'Bilingual AR/EN', ar: 'ثنائي اللغة' }, description: { en: 'Full Arabic and English support with RTL layout — built for the Arab gaming community.', ar: 'دعم كامل للعربية والإنجليزية مع تخطيط RTL — مصمم لمجتمع الألعاب العربي.' } },
    ],
    stats: [
      { value: '11', label: { en: 'Unique Roles', ar: 'دور فريد' } },
      { value: '3', label: { en: 'Teams', ar: 'فرق' } },
      { value: '∞', label: { en: 'Game Nights', ar: 'ليالي لعب' } },
    ],
    storeLinks: [],
    heroImage: 'https://assets.buriedgames.com/images/games/arrab/hero-bg.png',
    heroImageHint: 'dark mafia noir lounge',
    heroVideo: null,
    imageUrl: 'https://assets.buriedgames.com/images/games/arrab/hero-right.png',
    imageHint: 'mafia godfather silhouette',
    videoUrl: null,
    gallery: [
      { url: 'https://assets.buriedgames.com/images/games/arrab/hero-bg.png', hint: 'Noir lounge background' },
      { url: 'https://assets.buriedgames.com/images/games/arrab/hero-right.png', hint: 'Godfather silhouette' },
    ],
    roles: [
      { id: 'godfather', team: 'mafia', name: { en: 'Godfather', ar: 'العرّاب' }, action: { en: 'Kill', ar: 'قتل' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/godfather.png' },
      { id: 'mafia-member', team: 'mafia', name: { en: 'Mafia Member', ar: 'عضو المافيا' }, action: { en: 'Kill', ar: 'قتل' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/mafia-member.png' },
      { id: 'barman', team: 'mafia', name: { en: 'Barman', ar: 'البارمان' }, action: { en: 'Block', ar: 'حظر' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/barman.png' },
      { id: 'doctor', team: 'town', name: { en: 'Doctor', ar: 'الدكتور' }, action: { en: 'Save', ar: 'إنقاذ' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/doctor.png' },
      { id: 'detective', team: 'town', name: { en: 'Detective', ar: 'المحقق' }, action: { en: 'Investigate', ar: 'تحقيق' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/detective.png' },
      { id: 'bodyguard', team: 'town', name: { en: 'Bodyguard', ar: 'الحارس الشخصي' }, action: { en: 'Protect', ar: 'حماية' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/bodyguard.png' },
      { id: 'sniper', team: 'town', name: { en: 'Sniper', ar: 'القنّاص' }, action: { en: 'Snipe', ar: 'قنص' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/sniper.png' },
      { id: 'villager', team: 'town', name: { en: 'Villager', ar: 'المواطن' }, action: { en: 'Vote', ar: 'تصويت' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/villager.png' },
      { id: 'jester', team: 'neutral', name: { en: 'Jester', ar: 'المهرج' }, action: { en: 'Deceive', ar: 'خداع' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/jester.png' },
      { id: 'serial-killer', team: 'neutral', name: { en: 'Serial Killer', ar: 'القاتل المتسلسل' }, action: { en: 'Kill', ar: 'قتل' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/serial-killer.png' },
      { id: 'kamikaze', team: 'town', name: { en: 'Kamikaze', ar: 'الانتحاري' }, action: { en: 'Sacrifice', ar: 'تضحية' }, image: 'https://assets.buriedgames.com/images/games/arrab/roles/kamikaze.png' },
    ],
  },
  {
    id: 'nabsh',
    slug: 'nabsh',
    title: 'Nabsh',
    status: 'released',
    engine: 'Next.js',
    logoUrl: 'https://assets.buriedgames.com/images/nabsh_logo.png',
    description: {
      en: 'A thrilling trivia web game that tests your knowledge on a wide range of topics. Challenge friends and climb the ranks!',
      ar: 'لعبة معلومات عامة مثيرة على الويب تختبر معلوماتك في مجموعة واسعة من المواضيع. تحدَّ أصدقاءك وتصدر قائمة المتصدرين!',
    },
    longDescription: {
        en: 'Nabsh is the ultimate trivia challenge! Compete with players in real-time, answer questions across various categories like history, culture, sports, and more. With a sleek design, engaging gameplay, and social features, Nabsh is the perfect game to prove your knowledge and have fun with friends and family.',
        ar: 'نبش هو التحدي النهائي للمعلومات العامة! تنافس مع اللاعبين في الوقت الفعلي، وأجب عن أسئلة في فئات متنوعة مثل التاريخ والثقافة والرياضة والمزيد. بفضل التصميم الأنيق واللعب الجذاب والميزات الاجتماعية، يعد نبش اللعبة المثالية لإثبات معرفتك والاستمتاع مع الأصدقاء والعائلة.'
    },
    features: [
        { icon: 'Users', title: { en: 'Live Multiplayer', ar: 'لعب جماعي مباشر' }, description: { en: 'Challenge friends or other players in exciting real-time trivia battles.', ar: 'تحدَّ الأصدقاء أو اللاعبين الآخرين في معارك معلومات عامة مثيرة في الوقت الفعلي.' } },
        { icon: 'Puzzle', title: { en: 'Diverse Categories', ar: 'فئات متنوعة' }, description: { en: 'Thousands of questions covering culture, history, sports, and more.', ar: 'آلاف الأسئلة التي تغطي الثقافة والتاريخ والرياضة والمزيد.' } },
        { icon: 'Trophy', title: { en: 'Leaderboards', ar: 'لوحات الصدارة' }, description: { en: 'Compete for the top spot and showcase your trivia prowess.', ar: 'تنافس على المركز الأول واستعرض براعتك في المعلومات العامة.' } },
        { icon: 'Smartphone', title: { en: 'Sleek & Modern', ar: 'أنيق وعصري' }, description: { en: 'Enjoy a beautiful and user-friendly interface on all your devices.', ar: 'استمتع بواجهة جميلة وسهلة الاستخدام على جميع أجهزتك.' } },
    ],
    stats: [
        { value: '50+', label: { en: 'Categories', ar: 'فئات' } },
        { value: '200+', label: { en: 'Subcategories', ar: 'فئات فرعية' } },
        { value: '10K+', label: { en: 'Questions', ar: 'أسئلة' } },
    ],
    storeLinks: [
        { store: 'web', url: 'https://nabsh.fun', imageUrl: null, label: { en: 'Visit Website', ar: 'زيارة الموقع' } },
    ],
    heroImage: 'https://assets.buriedgames.com/images/games/nabsh/hero.png',
    heroImageHint: 'trivia quiz brain',
    heroVideo: 'https://nabsh.fun/videos/hero-animation-video.mp4',
    imageUrl: 'https://assets.buriedgames.com/images/games/nabsh/hero.png',
    imageHint: 'trivia game',
    videoUrl: 'https://www.youtube.com/embed/F0WBKweQ-NM',
    categories: [
      { name: { en: 'Celebrities', ar: 'المشاهير' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/celebrities.jpg' },
      { name: { en: 'Movies', ar: 'افلام' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/movies.webp' },
      { name: { en: 'Sports', ar: 'رياضة' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/sports.webp' },
      { name: { en: 'Cars', ar: 'سيارات' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/cars.webp' },
      { name: { en: 'Animals', ar: 'حيوانات' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/animals.webp' },
      { name: { en: 'Cartoon', ar: 'رسوم متحركه' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/cartoon.webp' },
      { name: { en: 'Video Games', ar: 'الالعاب' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/videogames.jpg' },
      { name: { en: 'Songs', ar: 'اغاني' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/songs.webp' },
      { name: { en: 'Kuwait', ar: 'الكويت' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/kuwait.webp' },
      { name: { en: 'Mathematics', ar: 'رياضيات' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/math.webp' },
      { name: { en: 'Plays', ar: 'مسرحيات' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/plays.webp' },
      { name: { en: 'Perfumes', ar: 'عطورات عالميه' }, image: 'https://assets.buriedgames.com/images/games/nabsh/categories/perfumes.jpg' },
    ],
    gallery: [],
  },
  {
    id: 'power-of-bombs',
    slug: 'power-of-bombs',
    title: 'Power of Bombs',
    status: 'development',
    engine: 'Unreal Engine',
    logoUrl: '/components/images/powerofbombsIconTransparent.png',
    description: {
      en: 'An explosive action-packed arcade game. Strategize your way through challenging levels, plant bombs, and blast your enemies to bits!',
      ar: 'لعبة أركيد مليئة بالإثارة والمتفجرات. ضع استراتيجيتك عبر مستويات صعبة ، وازرع القنابل ، وانسف أعدائك إلى أشلاء!',
    },
    longDescription: {
        en: 'Dive into the explosive world of Power of Bombs! This is a top-down, action-packed arcade game that challenges your strategic thinking and reflexes. Navigate through intricate mazes, plant powerful bombs to clear paths and defeat unique enemies. With a variety of power-ups, challenging boss fights, and a retro-inspired aesthetic, Power of Bombs delivers hours of addictive fun.',
        ar: 'انغمس في عالم Power of Bombs المتفجر! هذه لعبة أركيد مليئة بالإثارة من منظور علوي تتحدى تفكيرك الاستراتيجي وردود أفعالك. تنقل عبر متاهات معقدة ، وازرع قنابل قوية لتمهيد الطرق وهزيمة الأعداء الفريدين. مع مجموعة متنوعة من معززات القوة ومعارك الزعماء الصعبة والجمالية المستوحاة من الطراز القديم ، تقدم Power of Bombs ساعات من المرح الإدماني.'
    },
    features: [
        { icon: 'Puzzle', title: { en: 'Strategic Levels', ar: 'مستويات استراتيجية' }, description: { en: 'Dozens of hand-crafted levels to test your wits.', ar: 'عشرات المستويات المصممة يدويًا لاختبار ذكائك.' } },
        { icon: 'Users', title: { en: 'Multiplayer Mayhem', ar: 'فوضى متعددة اللاعبين' }, description: { en: 'Compete against friends in local multiplayer battles.', ar: 'تنافس ضد الأصدقاء في معارك محلية متعددة اللاعبين.' } },
        { icon: 'Bolt', title: { en: 'Powerful Power-ups', ar: 'معززات قوة قوية' }, description: { en: 'Collect upgrades to increase your bomb range and power.', ar: 'اجمع الترقيات لزيادة مدى قنابلتك وقوتها.' } },
        { icon: 'ShieldCheck', title: { en: 'Epic Boss Fights', ar: 'معارك زعماء ملحمية' }, description: { en: 'Face off against challenging bosses with unique mechanics.', ar: 'واجه زعماء صعبين بآليات فريدة.' } },
    ],
    stats: [],
    storeLinks: [],
    heroImage: 'POPBackground.jpg',
    heroImageHint: 'POPBackground game art',
    heroVideo: null,
    imageUrl: 'https://assets.buriedgames.com/images/buriedgames_logo.png',
    imageHint: 'explosion action',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    gallery: [
      { url: 'POPOverview.jpg', hint: 'POPOverview gameplay' },
    ],
  },
  {
    id: 'koutq8',
    slug: 'koutq8',
    title: 'KoutQ8',
    status: 'released',
    engine: 'Unity',
    logoUrl: '/components/images/Koutq8Logo.png',
    description: {
      en: 'A digital adaptation of the popular traditional card game Kout. Play with friends online and prove you are the Kout master.',
      ar: 'نسخة رقمية من لعبة الورق التقليدية الشهيرة الكوت. العب مع الأصدقاء عبر الإنترنت وأثبت أنك سيد الكوت.',
    },
    longDescription: {
        en: 'Experience the classic card game Kout like never before. KoutQ8 brings the beloved traditional game to your fingertips, featuring polished graphics, smooth online multiplayer, and challenging AI opponents. Team up with a partner, bid on hands, and strategize to win. Whether you\'re a seasoned veteran or new to the game, KoutQ8 is the definitive digital Kout experience.',
        ar: 'جرب لعبة الكوت الكلاسيكية كما لم يحدث من قبل. KoutQ8 تجلب اللعبة التقليدية المحبوبة إلى أطراف أصابعك ، وتتميز برسومات مصقولة ، ولعب سلس متعدد اللاعبين عبر الإنترنت ، وخصوم ذكاء اصطناعي صعبين. كوّن فريقًا مع شريك ، وراهن على توزيعات الورق ، وضع استراتيجية للفوز. سواء كنت لاعبًا متمرسًا أو جديدًا في اللعبة ، فإن KoutQ8 هي تجربة الكوت الرقمية النهائية.'
    },
    features: [
        { icon: 'Users', title: { en: 'Online Multiplayer', ar: 'لعب جماعي عبر الإنترنت' }, description: { en: 'Play with friends and players from around the world.', ar: 'العب مع الأصدقاء واللاعبين من جميع أنحاء العالم.' } },
        { icon: 'Bot', title: { en: 'Challenging AI', ar: 'ذكاء اصطناعي صعب' }, description: { en: 'Hone your skills against our advanced AI partner and opponents.', ar: 'اصقل مهاراتك ضد شريكنا وخصومنا المتقدمين في الذكاء الاصطناعي.' } },
        { icon: 'Trophy', title: { en: 'Leaderboards & Stats', ar: 'لوحات الصدارة والإحصائيات' }, description: { en: 'Track your progress and climb the ranks to become the best.', ar: 'تتبع تقدمك وتسلق المراتب لتصبح الأفضل.' } },
        { icon: 'Smartphone', title: { en: 'Cross-Platform Play', ar: 'لعب عبر المنصات' }, description: { en: 'Play on your favorite device, with support for mobile and PC.', ar: 'العب على جهازك المفضل ، مع دعم للجوال والكمبيوتر الشخصي.' } },
    ],
    stats: [],
    storeLinks: [
        { store: 'App Store', url: 'https://apps.apple.com/app/id6738164175', imageUrl: 'downloadAppStoreImage.png', label: null },
    ],
    heroImage: '',
    heroImageHint: 'playing cards',
    heroVideo: 'https://assets.buriedgames.com/videos/koutq8-hero.mp4',
    imageUrl: 'https://assets.buriedgames.com/images/buriedgames_logo.png',
    imageHint: 'card game',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    gallery: [
      { url: 'KoutQ8Image_1.png', hint: 'KoutQ8 gameplay screenshot 1' },
      { url: 'KoutQ8Image_2.png', hint: 'KoutQ8 gameplay screenshot 2' },
      { url: 'KoutQ8Image_3.png', hint: 'KoutQ8 gameplay screenshot 3' },
    ],
  },
  {
    id: 'luna-fantasy',
    slug: 'luna-fantasy',
    title: 'Luna Fantasy',
    status: 'released',
    engine: 'Next.js',
    logoUrl: 'https://assets.buriedgames.com/images/luna-fantasy_logo.png',
    description: {
      en: 'Official website for the Luna Fantasy Discord community - a massive fantasy universe featuring 200+ characters, a strategic card game, and immersive lore.',
      ar: 'الموقع الرسمي لمجتمع Luna Fantasy على Discord - عالم خيالي ضخم يضم أكثر من 200 شخصية، ولعبة بطاقات استراتيجية، وقصص غامرة.',
    },
    longDescription: {
        en: 'Luna Fantasy is a comprehensive companion platform for a thriving Discord fantasy community. The website showcases an interconnected universe with over 200 unique characters across 13 factions, a custom strategic card game with 7 rarity tiers, rich lore documenting The Great Chaos War, and a complete virtual economy system. Built with bilingual support for English and Arabic audiences.',
        ar: 'Luna Fantasy هي منصة شاملة لمجتمع Discord الخيالي المزدهر. يعرض الموقع عالمًا مترابطًا يضم أكثر من 200 شخصية فريدة عبر 13 فصيلة، ولعبة بطاقات استراتيجية مخصصة بـ 7 مستويات ندرة، وقصص غنية توثق حرب الفوضى العظمى، ونظام اقتصادي افتراضي كامل. مبني بدعم ثنائي اللغة للجماهير الإنجليزية والعربية.'
    },
    features: [
        { icon: 'Users', title: { en: 'Character Gallery', ar: 'معرض الشخصيات' }, description: { en: '200+ unique characters across 13 factions with detailed lore and profiles.', ar: 'أكثر من 200 شخصية فريدة عبر 13 فصيلة مع قصص وملفات تعريف مفصلة.' } },
        { icon: 'Puzzle', title: { en: 'Strategic Card Game', ar: 'لعبة بطاقات استراتيجية' }, description: { en: 'Custom card game system with 7 rarity tiers and 200+ collectible cards.', ar: 'نظام لعبة بطاقات مخصص مع 7 مستويات ندرة وأكثر من 200 بطاقة قابلة للجمع.' } },
        { icon: 'BookOpen', title: { en: 'Rich Lore & Chronicles', ar: 'قصص وسجلات غنية' }, description: { en: 'Epic narrative spanning The Great Chaos War and centuries of history.', ar: 'سرد ملحمي يمتد عبر حرب الفوضى العظمى وقرون من التاريخ.' } },
        { icon: 'Wallet', title: { en: 'Virtual Economy', ar: 'اقتصاد افتراضي' }, description: { en: 'Complete banking system with loans, trading, and VIP memberships.', ar: 'نظام مصرفي كامل مع قروض وتداول وعضويات VIP.' } },
    ],
    stats: [
        { value: '200+', label: { en: 'Characters', ar: 'شخصية' } },
        { value: '13', label: { en: 'Factions', ar: 'فصيلة' } },
        { value: '7', label: { en: 'Card Rarities', ar: 'مستويات ندرة' } },
    ],
    storeLinks: [
        { store: 'web', url: 'https://lunarian.com', imageUrl: null, label: { en: 'Visit Website', ar: 'زيارة الموقع' } },
    ],
    heroImage: 'https://assets.buriedgames.com/images/games/luna-fantasy/hero.png',
    heroImageHint: 'fantasy card game universe',
    heroVideo: null,
    imageUrl: 'https://assets.buriedgames.com/images/games/luna-fantasy/hero.png',
    imageHint: 'luna fantasy characters',
    videoUrl: null,
    gallery: [
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/our-characters.png', hint: 'Luna Fantasy characters gallery' },
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/card-legendary.png', hint: 'Legendary rarity card' },
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/card-epic.png', hint: 'Epic rarity card' },
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/champion.png', hint: 'Champion story art' },
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/char-sentinel.png', hint: 'Luna Sentinel character' },
      { url: 'https://assets.buriedgames.com/images/games/luna-fantasy/char-knight.png', hint: 'Luna Knight character' },
    ],
  },
  {
    id: 'gathered-by-the-light',
    slug: 'gathered-by-the-light',
    title: 'Gathered by the Light',
    status: 'completed',
    engine: 'Unity',
    logoUrl: 'https://assets.buriedgames.com/images/games/gbtl/logo.png',
    description: {
      en: 'A hand-crafted pixel-art 2D platformer about a young moth on a perilous journey through a dark forest to find a mysterious light. Built as a college capstone project.',
      ar: 'لعبة منصات ثنائية الأبعاد بفن البكسل عن فراشة صغيرة في رحلة خطيرة عبر غابة مظلمة للعثور على ضوء غامض. تم بناؤها كمشروع تخرج جامعي.',
    },
    longDescription: {
      en: 'Gathered by the Light is a heartfelt 2D pixel-art platformer that tells the story of a young moth separated from their parents, embarking on a dangerous journey through a dark, spider-infested forest in search of a mysterious light. Featuring hand-drawn pixel art, parallax scrolling environments, a grappling hook mechanic, an atmospheric intro comic, and a challenging spider boss fight — this game was developed as a university capstone project and represents the studio\'s roots in game design and interactive storytelling.',
      ar: 'Gathered by the Light هي لعبة منصات ثنائية الأبعاد بفن البكسل تحكي قصة فراشة صغيرة انفصلت عن والديها، وانطلقت في رحلة خطيرة عبر غابة مظلمة مليئة بالعناكب بحثًا عن ضوء غامض. تتميز بفن بكسل مرسوم يدويًا، وبيئات تمرير متوازية، وآلية خطاف تسلق، ومقدمة كوميكية جوية، ومعركة زعيم عنكبوت صعبة — تم تطوير هذه اللعبة كمشروع تخرج جامعي وتمثل جذور الاستوديو في تصميم الألعاب والسرد التفاعلي.',
    },
    features: [
      { icon: 'Puzzle', title: { en: 'Grappling Hook Mechanic', ar: 'آلية خطاف التسلق' }, description: { en: 'Swing through the forest canopy with a physics-based grappling hook system.', ar: 'تأرجح عبر مظلة الغابة مع نظام خطاف تسلق قائم على الفيزياء.' } },
      { icon: 'ShieldCheck', title: { en: 'Spider Boss Fight', ar: 'معركة زعيم العنكبوت' }, description: { en: 'Face a terrifying spider boss in an intense multi-phase battle.', ar: 'واجه زعيم عنكبوت مرعب في معركة متعددة المراحل.' } },
      { icon: 'Bolt', title: { en: 'Hand-Drawn Pixel Art', ar: 'فن بكسل مرسوم يدويًا' }, description: { en: 'Every sprite, tileset, and animation crafted pixel by pixel in Aseprite.', ar: 'كل رسم وبلاطة ورسوم متحركة مصنوعة بكسل ببكسل.' } },
      { icon: 'BookOpen', title: { en: 'Comic Intro Sequence', ar: 'مقدمة كوميكية' }, description: { en: 'A cinematic pixel-art comic that sets the stage for the moth\'s journey.', ar: 'كوميك بفن البكسل يمهد لرحلة الفراشة.' } },
    ],
    stats: [
      { value: '5', label: { en: 'Comic Slides', ar: 'شرائح كوميك' } },
      { value: '10+', label: { en: 'Levels', ar: 'مستويات' } },
      { value: '1', label: { en: 'Boss Fight', ar: 'معركة زعيم' } },
    ],
    storeLinks: [],
    heroImage: 'https://assets.buriedgames.com/images/games/gbtl/poster.png',
    heroImageHint: 'pixel art moth forest',
    heroVideo: 'https://assets.buriedgames.com/videos/gbtl-hero.mp4',
    imageUrl: 'https://assets.buriedgames.com/images/games/gbtl/poster.png',
    imageHint: 'pixel art platformer',
    videoUrl: null,
    gallery: [
      { url: 'https://assets.buriedgames.com/images/games/gbtl/poster.png', hint: 'Game poster' },
      { url: 'https://assets.buriedgames.com/images/games/gbtl/start-screen.png', hint: 'Start screen' },
      { url: 'https://assets.buriedgames.com/images/games/gbtl/tileset.png', hint: 'Level tileset' },
    ],
    comicSlides: [
      'https://assets.buriedgames.com/images/games/gbtl/comic-1.png',
      'https://assets.buriedgames.com/images/games/gbtl/comic-2.png',
      'https://assets.buriedgames.com/images/games/gbtl/comic-3.png',
      'https://assets.buriedgames.com/images/games/gbtl/comic-4.png',
      'https://assets.buriedgames.com/images/games/gbtl/comic-5.png',
    ],
    characters: [
      { name: { en: 'Moth (Hero)', ar: 'الفراشة (البطل)' }, sprite: 'https://assets.buriedgames.com/images/games/gbtl/moth-jump.gif' },
      { name: { en: 'Father', ar: 'الأب' }, sprite: 'https://assets.buriedgames.com/images/games/gbtl/father.gif' },
      { name: { en: 'Mother', ar: 'الأم' }, sprite: 'https://assets.buriedgames.com/images/games/gbtl/mother.gif' },
      { name: { en: 'Spider Boss', ar: 'زعيم العنكبوت' }, sprite: 'https://assets.buriedgames.com/images/games/gbtl/spider.gif' },
    ],
    designAssets: [
      { label: { en: 'Grappling Hook', ar: 'خطاف التسلق' }, image: 'https://assets.buriedgames.com/images/games/gbtl/grappling-hook.gif' },
      { label: { en: 'Checkpoint', ar: 'نقطة حفظ' }, image: 'https://assets.buriedgames.com/images/games/gbtl/checkpoint.gif' },
      { label: { en: 'Jump Hint', ar: 'تلميح القفز' }, image: 'https://assets.buriedgames.com/images/games/gbtl/hint-jump.gif' },
      { label: { en: 'Movement', ar: 'الحركة' }, image: 'https://assets.buriedgames.com/images/games/gbtl/hint-move.gif' },
    ],
    trailerUrl: 'https://assets.buriedgames.com/videos/gbtl-trailer.mp4',
  },
];

    
